import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { tracks, experiences, education, publications, reviewService, profile } from '@/data/portfolio';
import { metadata } from '@/lib/site';
import { ResumeLink } from '@/components/interactive';
export const dynamicParams=false;
export const generateStaticParams=()=>tracks.map(t=>({slug:t.id}));
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const t=tracks.find(t=>t.id===slug);return t?metadata(t.name,t.summary,`/tracks/${t.id}`):{};}
export default async function TrackPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const t=tracks.find(t=>t.id===slug);if(!t)notFound();const relevant=publications.filter(p=>p.trackIds.includes(t.id));return <article className="shell track-page"><Link className="text-link back-link" href="/"><ArrowLeft size={16}/>All expertise</Link><div className="track-intro"><p className="eyebrow">{t.name}</p><p className="print-name">{profile.name} · {profile.location} · {profile.email || 'Email to be added'}</p><h1>{t.headline}</h1><p className="lead">{t.summary}</p><div className="hero-buttons"><ResumeLink trackId={t.id}/><Link className="button secondary" href="/contact/">Discuss this role <ArrowUpRight size={17}/></Link></div></div><div className="track-body"><div><section className="track-section"><h2>Core competencies</h2><p className="skill-legend">Applied: professional use · Research: doctoral or research use · Developing: current study</p><div className="skill-grid">{t.skills.map(([name,level])=><div className="skill" key={name}><span>{name}</span><span className={`proficiency ${level.toLowerCase()}`}><i aria-hidden="true"/>{level}</span></div>)}</div></section><section className="track-section"><h2>Relevant experience & projects</h2>{t.experienceIds.map(id=>{const e=experiences.find(x=>x.id===id)!;return <div key={id} className="experience"><div className="experience-heading"><h3>{e.title}</h3><span>{e.period}</span></div><p>{e.organization}</p><ul>{e.variants[t.id]?.map(b=><li key={b}>{b}</li>)}</ul></div>})}</section></div><aside className="track-aside"><section><p className="eyebrow">Technical toolkit</p><h2>Tools & methods</h2><div className="tags">{t.tools.map(x=><span key={x}>{x}</span>)}</div></section><section><p className="eyebrow">Foundation</p><h2>Education & development</h2>{t.educationIds.map(id=>{const e=education.find(x=>x.id===id)!;return <div className="education" key={id}><h3>{e.title}</h3><p>{e.institution}</p><small>{e.detail}</small></div>})}</section><section><h2>Research & service</h2>{relevant.length?relevant.map(p=><p key={p.id}>{p.title}{p.doi&&<> · <a className="inline-link" href={`https://doi.org/${p.doi}`}>DOI</a></>}</p>):<p className="muted">Relevant publication citations have not yet been added.</p>}{t.id==='pavement'&&<ul>{reviewService.map(x=><li key={x}>{x}</li>)}</ul>}<Link href="/publications/" className="text-link">Publications & review service <ArrowUpRight size={16}/></Link></section></aside></div><div className="track-bottom"><div><h2>Let’s talk about your team.</h2><p>{profile.relocation} · {t.name}</p></div><Link href="/contact/" className="button">Get in touch <ArrowUpRight size={17}/></Link></div></article>}
