'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowDownToLine, ArrowUpRight, ChevronDown, Menu, Moon, Sun, X } from 'lucide-react';
import { profile, tracks, type TrackId } from '@/data/portfolio';
import { asset } from '@/lib/site';

export function ResumeLink({ trackId, className='button' }: {trackId?:TrackId;className?:string}) {
 const pathname=usePathname(); const [last,setLast]=useState<string|null>(null);
 useEffect(()=>{try { const active=tracks.find(t=>pathname.includes(`/tracks/${t.id}`)); if(active) sessionStorage.setItem('portfolio-track',active.id); setLast(active?.id || sessionStorage.getItem('portfolio-track')); } catch {setLast(null);} },[pathname]);
 const track=tracks.find(t=>t.id===(trackId || last));
 return <a className={className} href={asset(track?.resume || profile.resume)} download aria-label={`Download ${track?.name || 'general'} resume${profile.resumeIsPlaceholder?' (placeholder PDF)':''}`}><ArrowDownToLine size={17}/>{trackId?'Track resume':'Download resume'}{profile.resumeIsPlaceholder && <span className="pdf-label">Sample</span>}</a>;
}
export function Header() {
 const [dark,setDark]=useState(false); const [open,setOpen]=useState(false); const path=usePathname(); const drawer=useRef<HTMLDivElement>(null); const opener=useRef<HTMLButtonElement>(null); const details=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{ const media=matchMedia('(prefers-color-scheme: dark)'); const sync=()=>{let saved=null;try{saved=localStorage.getItem('theme')}catch{} const next=saved?saved==='dark':media.matches;document.documentElement.dataset.theme=next?'dark':'light';setDark(next);}; sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync);},[]);
 useEffect(()=>{setOpen(false);if(details.current)details.current.open=false;},[path]);
 useEffect(()=>{if(!open)return; const previous=document.body.style.overflow;document.body.style.overflow='hidden';drawer.current?.querySelector<HTMLElement>('button')?.focus(); const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);opener.current?.focus();}if(event.key==='Tab'){const els=Array.from(drawer.current?.querySelectorAll<HTMLElement>('a,button')||[]);const first=els[0],last=els[els.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key);};},[open]);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(details.current&&!details.current.contains(e.target as Node))details.current.open=false;};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[]);
 const toggle=()=>{const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('theme',next?'dark':'light')}catch{}};
 const links=<>{['About','Projects','Publications','Certifications','Contact'].map(n=><Link key={n} href={`/${n.toLowerCase()}/`} aria-current={path===`/${n.toLowerCase()}/`?'page':undefined}>{n}</Link>)}</>;
 return <header className="header"><div className="header-inner"><Link href="/" className="brand" aria-label={`${profile.name} home`}><span className="monogram">{profile.initials}</span><span>{profile.name.split(' ')[0]}<br/><b>{profile.name.split(' ').slice(1).join(' ')}</b></span></Link><nav className="desktop-nav" aria-label="Main navigation"><details ref={details} className="track-menu" onKeyDown={e=>{if(e.key==='Escape'){e.currentTarget.open=false;e.currentTarget.querySelector('summary')?.focus();}}}><summary>Expertise <ChevronDown size={15}/></summary><div className="mega">{tracks.map((t,i)=><Link key={t.id} href={`/tracks/${t.id}/`}><span className="eyebrow">0{i+1}</span><span>{t.name}<small>{t.short}</small></span></Link>)}</div></details>{links}</nav><div className="header-actions"><button className="icon-button" onClick={toggle} aria-label={dark?'Switch to light mode':'Switch to dark mode'}>{dark?<Sun size={20}/>:<Moon size={20}/>}</button><div className="header-resume"><ResumeLink className="button small"/></div><button ref={opener} className="icon-button mobile-menu" aria-label="Open navigation" aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(true)}><Menu/></button></div></div>{open&&<div className="drawer-backdrop" onClick={()=>{setOpen(false);opener.current?.focus()}}><div id="mobile-navigation" ref={drawer} className="drawer" role="dialog" aria-modal="true" aria-label="Navigation" onClick={e=>e.stopPropagation()}><button className="icon-button drawer-close" aria-label="Close navigation" onClick={()=>{setOpen(false);opener.current?.focus()}}><X/></button><nav aria-label="Mobile navigation"><Link href="/">Home</Link>{links}<p className="eyebrow">Explore expertise</p>{tracks.map(t=><Link key={t.id} href={`/tracks/${t.id}/`}>{t.name}</Link>)}<ResumeLink/></nav></div></div>}</header>;
}
export function Reveal({children,className=''}:{children:React.ReactNode;className?:string}) {const reduced=useReducedMotion();return <motion.div className={className} initial={false} whileInView={reduced?{}:{opacity:[0.85,1],y:[10,0]}} viewport={{once:true,amount:.08}} transition={{duration:.4}}>{children}</motion.div>}
export function PageTransition({children}:{children:React.ReactNode}) {const path=usePathname();const reduced=useReducedMotion();return <AnimatePresence mode="wait" initial={false}><motion.div key={path} initial={reduced?false:{opacity:.8,y:5}} animate={{opacity:1,y:0}} transition={{duration:.2}}>{children}</motion.div></AnimatePresence>}
export function HiringSelector(){const router=useRouter();return <div className="hiring-selector"><label htmlFor="hiring">What are you hiring for?</label><select id="hiring" defaultValue="" onChange={e=>{if(e.target.value)router.push(`/tracks/${e.target.value}/`)}}><option value="" disabled>Select a role track</option>{tracks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><ArrowUpRight size={20} aria-hidden="true"/></div>}
